### ISSUE TITLE
to do list next week 6 nov-12nov

### ISSUE THREAD

**Issue by Start-advancer** [Start-advancer/Graduation_Project#2]
1.replicate analysis remain
2.starting related work 
3.upload theis te to my github repo and read section

**Comment by gulcalikli** [comment]
- [ ] complete the remaining replication studies listed in the excel file that you (Feng) prepared
- [ ] Upload the MSc thesis template to your GitHub repo
- [ ] complete writing the first version of the "Related Work" section of your thesis and write the "Related Work" section in the MS Word thesis template
